core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Product views urls
    path("product_list/", views.product_List, name="product_list"),
    path("product_create/", views.product_Create, name="product_create"),
    path("product_update/<int:id>/", views.product_Update, name="product_update"),
    path("product_delete/<int:id>/", views.product_Delete, name="product_delete"),
    # Brands views urls
    path("brand_list/", views.brands_List, name="brand_list"),
    path("brand_create/", views.brands_Create, name="brand_create"),
    path("brand_update/<int:id>/", views.brands_Update, name="brand_update"),
    path("brand_delete/<int:id>/", views.brands_Delete, name="brand_delete"),
    # Supplier views urls
    path("supplier_list/", views.supplier_List, name="supplier_list"),
    path("supplier_create/", views.suppliers_Create, name="supplier_create"),
    path("supplier_update/<int:id>/", views.suppliers_Update, name="supplier_update"),
    path("supplier_delete/<int:id>/", views.suppliers_Delete, name="supplier_delete"),
    # Category views urls
    path("category_list/", views.category_list, name="category_list"),
    path("category_create/", views.category_Create, name="category_create"),
    path("category_update/<int:id>/", views.category_Update, name="category_update"),
    path("category_delete/<int:id>/", views.category_Delete, name="category_delete"),
    # Signup
    path("signup/", views.signup, name="signup"),
    path("logout/", views.signout, name="logout"),
    path("signin/", views.signin, name="signin"),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import Product, Brand, Supplier, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "description",
            "price",
            "stock",
            "brand",
            "categories",
            "line",
            "supplier",
            "expiration_date",
            "image",
            "state",
        ]


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ["description", "state"]


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ["name", "ruc", "address", "phone", "state"]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["description", "state"]

core/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from core.models import Product, Brand, Supplier, Category
from core.forms import ProductForm, BrandForm, SupplierForm, CategoryForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
import re

# Create your views here.
def home(request):
    data = {"title1": "FUTI", "title2": "Super Mercado Economico"}

    return render(request, "core/home.html", data)


def is_password_strong(password):
    # Verificar longitud mínima
    if len(password) < 8:
        return False, "La contraseña debe tener al menos 8 caracteres."
    
    # Verificar que contenga al menos una letra
    if not re.search(r"[a-zA-Z]", password):
        return False, "La contraseña debe contener al menos una letra."
    
    # Verificar que contenga al menos un número
    if not re.search(r"\d", password):
        return False, "La contraseña debe contener al menos un número."
    
    # Verificar que contenga al menos un símbolo
    if not re.search(r"[!@#$%^&*(),.?\":{}|<>-_]", password):
        return False, "La contraseña debe contener al menos un símbolo."
    
    return True, ""

def signup(request):
    if request.method == "GET":
        return render(request, "core/signup/signup.html", {"form": UserCreationForm()})
    else:
        username = request.POST["username"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]

        if password1 != password2:
            return render(
                request,
                "core/signup/signup.html",
                {"form": UserCreationForm(), "error": "Las contraseñas no coinciden."},
            )

        if password1 == username:
            return render(
                request,
                "core/signup/signup.html",
                {"form": UserCreationForm(), "error": "La contraseña no puede ser igual al nombre de usuario."},
            )

        is_strong, message = is_password_strong(password1)
        if not is_strong:
            return render(
                request,
                "core/signup/signup.html",
                {"form": UserCreationForm(), "error": message},
            )

        try:
            user = User.objects.create_user(
                username=username,
                password=password1,
            )
            user.save()
            login(request, user)
            return redirect("home")
        except IntegrityError:
            return render(
                request,
                "core/signup/signup.html",
                {"form": UserCreationForm(), "error": "El usuario ya existe."},
            )


def signout(request):
    logout(request)
    return redirect("home")


def signin(request):
    if request.method == "GET":
        return render(request, "core/signin/signin.html", {"form": AuthenticationForm})
    else:
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"],
        )
        if user is None:
            return render(request, "core/signin/signin.html", 
                          {"form": AuthenticationForm,
                           'error': 'Usuario o contraseña es incorrecta.'
                           })
        else:
            login(request, user)
            return redirect('home')


# Product Views
def product_List(request):
    data = {"title1": "Products", "title2": "Consulta de Productos"}

    products = Product.objects.all()
    data["products"] = products

    return render(request, "core/products/list.html", data)


# Create Product
@login_required
def product_Create(request):
    data = {"title1": "Productos", "title2": "Ingreso de Productos"}

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect("core:product_list")
        else:
            data["form"] = form  # Pasar el formulario con errores
    else:
        data["form"] = ProductForm()  # Formulario sin datos

    return render(request, "core/products/form.html", data)


# Update Product
@login_required
def product_Update(request, id):
    data = {"title1": "Productos", "title2": ">Edicion De Productos"}
    product = Product.objects.get(pk=id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect("core:product_list")
    else:
        form = ProductForm(instance=product)
        data["form"] = form
    return render(request, "core/products/form.html", data)


# Delete Product
@login_required
def product_Delete(request, id):
    product = Product.objects.get(pk=id)
    data = {"title1": "Eliminar", "title2": "Eliminar Un Producto", "product": product}
    if request.method == "POST":
        product.delete()
        return redirect("core:product_list")

    return render(request, "core/products/delete.html", data)


# Brands Views
def brands_List(request):
    data = {"title1": "Brands", "title2": "Consulta de Marcas"}

    brands = Brand.objects.all()
    data["brands"] = brands
    return render(request, "core/brands/list.html", data)


# Brands Create
@login_required
def brands_Create(request):
    data = {"title1": "Marcas", "title2": "Crear Marcas"}

    if request.method == "POST":
        form = BrandForm(request.POST, request.FILES)
        if form.is_valid():
            brand = form.save(commit=False)
            brand.user = request.user
            brand.save()
            return redirect("core:brand_list")

    else:
        data["form"] = BrandForm()  # controles formulario sin datos

    return render(request, "core/brands/form.html", data)


# Brands Update
@login_required
def brands_Update(request, id):
    data = {"title1": "Marcas", "title2": "Edicion De Marcas"}
    brand = Brand.objects.get(pk=id)
    if request.method == "POST":
        form = BrandForm(request.POST, request.FILES, instance=brand)
        if form.is_valid():
            form.save()
            return redirect("core:brand_list")
    else:
        form = BrandForm(instance=brand)
        data["form"] = form
    return render(request, "core/brands/form.html", data)


# Brands Delete
@login_required
def brands_Delete(request, id):
    brand = Brand.objects.get(pk=id)
    data = {"title1": "Eliminar", "title2": "Eliminar Un Producto", "brand": brand}
    if request.method == "POST":
        brand.delete()
        return redirect("core:brand_list")

    return render(request, "core/brands/delete.html", data)


# Supplier Views
def supplier_List(request):
    data = {"title1": "Suppliers", "title2": "Consulta de proveedores"}

    suppliers = Supplier.objects.all()
    data["suppliers"] = suppliers
    return render(request, "core/suppliers/list.html", data)


# Suppliers Create
@login_required
def suppliers_Create(request):
    data = {"title1": "Proveedores", "title2": "Crear Proveedores"}

    if request.method == "POST":
        try:
            form = SupplierForm(request.POST, request.FILES)
            if form.is_valid():
                brand = form.save(commit=False)
                brand.user = request.user
                brand.save()
                return redirect("core:supplier_list")
            
        except:
            data['form'] = form
            return render(request, 'core/suppliers/form.html', data)
    else:
        data["form"] = SupplierForm()  # controles formulario sin datos

    return render(request, "core/suppliers/form.html", data)


# Suppliers Update
@login_required
def suppliers_Update(request, id):
    data = {"title1": "Proveedor", "title2": "Edicion De Proveedores"}
    supplier = Supplier.objects.get(pk=id)
    if request.method == "POST":
        form = SupplierForm(request.POST, request.FILES, instance=supplier)
        if form.is_valid():
            form.save()
            return redirect("core:supplier_list")
    else:
        form = SupplierForm(instance=supplier)
        data["form"] = form
    return render(request, "core/suppliers/form.html", data)

@login_required
def suppliers_Delete(request, id):
    supplier = Supplier.objects.get(pk=id)
    data = {
        "title": "Eliminar",
        "title2": "Eliminar un Proveedor",
        "supplier": supplier,
    }
    if request.method == "POST":
        supplier.delete()
        return redirect("core:supplier_list")

    return render(request, "core/suppliers/delete.html", data)


# Category View
def category_list(request):
    data = {"title1": "Category", "title2": "Consulta de Categorias"}
    category = Category.objects.all()
    data["category"] = category
    return render(request, "core/category/list.html", data)

@login_required
def category_Create(request):
    data = {"title1": "Categorias", "title2": "Crear Categorias"}
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect("core:category_list")
    else:
        data["form"] = CategoryForm()

    return render(request, "core/category/form.html", data)

@login_required
def category_Update(request, id):
    data = {"title1": "Categorias", "title2": "Edicion de Categorias"}
    category = Category.objects.get(pk=id)
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()

templates/core/brands/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="form-container">
    <form class="form-container" method="POST">
     {% csrf_token %}
     <h1 class="title">{{ title2 }}</h1>
     <h2>¿Desea Eliminar la Marca?
        <span> ID: {{ brand.id }} - {{ brand.description }}</span>
     </h2>
     <div>
         <button class="btn blue" type="submit">Eliminar</button>
         <a class="btn red" href="{% url 'core:brand_list' %}" >Regresar</a>
     </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/core/brands/form.html
{% extends 'base.html' %}
{% block content %}
 <div class="container">
  <div class="form-container">
    <h2 class="title">{{title2}}</h2>
   
    <form method="post" enctype="multipart/form-data" class="card card-body">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-outline-success">
            <a href={% url 'core:brand_list' %} class="btn btn-outline-danger"> Cancelar </a>
        </div>
    </form>
</div>
</div>
{% endblock content  %}

templates/core/brands/list.html
{% extends 'base.html' %}
{% block content %}
   <div class="table-container">
    <br>
    <h1 class="title">{{ title2 }}</h1>
    <table class="styled-table">
      <thead>
        <tr>
          <th>Descripcion</th>
          <th>Estado</th>
          <th>Acciones</th>


      </tr>
      </thead>
      <tbody>
        {% for item in brands %}
          <tr>
          <td>{{item.description}}</td>
          <td>{% if item.state %}
            ✔
           {% else %}
            ➖
           {% endif %}
       </td>
  
          <td>
            <a href={% url 'core:brand_update' item.id %}>✏️</a>
            <a href={% url 'core:brand_delete' item.id %}>❌</a>
          </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
     <div class="form-group">
      <a class="btn btn-secondary" href={% url 'core:brand_create' %}>Nueva Marca</a>
     </div>
  </div>
  <style>
    .table-container {
        margin: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f9f9f9;
    }
    
    .title {
        text-align: center;
        font-size: 2em;
        color: #333;
    }
    
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: 'Arial', sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    
    .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    
    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
    }
    
    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }
    
    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }
    
    .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
    
    .styled-table tbody tr.active-row {
        font-weight: bold;
        color: #009879;
    }
    
    .form-group {
        text-align: center;
        margin-top: 20px;
    }
    
    .btn {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
    }
    
    .btn-secondary {
        background-color: #6c757d;
    }
    
    .btn:hover {
        background-color: #0056b3;
    }
    
    .btn-secondary:hover {
        background-color: #5a6268;
    }
    </style>
{% endblock content  %}