core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Product views urls
    path("product_list/", views.product_List, name="product_list"),
    path("product_create/", views.product_Create, name="product_create"),
    path("product_update/<int:id>/", views.product_Update, name="product_update"),
    path("product_delete/<int:id>/", views.product_Delete, name="product_delete"),
    # Brands views urls
    path("brand_list/", views.brands_List, name="brand_list"),
    path("brand_create/", views.brands_Create, name="brand_create"),
    path("brand_update/<int:id>/", views.brands_Update, name="brand_update"),
    path("brand_delete/<int:id>/", views.brands_Delete, name="brand_delete"),
    # Supplier views urls
    path("supplier_list/", views.supplier_List, name="supplier_list"),
    path("supplier_create/", views.suppliers_Create, name="supplier_create"),
    path("supplier_update/<int:id>/", views.suppliers_Update, name="supplier_update"),
    path("supplier_delete/<int:id>/", views.suppliers_Delete, name="supplier_delete"),
    # Category views urls
    path("category_list/", views.category_list, name="category_list"),
    path("category_create/", views.category_Create, name="category_create"),
    path("category_update/<int:id>/", views.category_Update, name="category_update"),
    path("category_delete/<int:id>/", views.category_Delete, name="category_delete"),
    # Signup
    path("signup/", views.signup, name="signup"),
    path("logout/", views.signout, name="logout"),
    path("signin/", views.signin, name="signin"),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href={% static 'css/main.css' %}>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
  <link rel="icon" href="../static/img/shopping-bag.ico" type="image/x-icon">
  <title>{% block title %}{{title1}}{% endblock title %}  </title>
</head>
<body>
  <header id="header">
    <a href={% url 'home' %} class="logo"><img src="../static/img/futi2.jpg" alt="Logo Futi"></a>
   <nav >
    <ul class="menu" >
      <li>
        <a href={% url 'home' %}> <i class="bi bi-house"></i> Inicio</a>
      </li>
      <li>
        <a href={% url 'core:product_list' %}> <i class="bi bi-cart"></i> Productos</a>
        
      </li>
      <li>
        <a href={% url 'core:brand_list' %}> <i class="bi bi-globe"></i> Marcas</a>
       
      </li>
      <li>
        <a href={% url 'core:supplier_list' %}><i class="bi bi-person-circle"></i> Proveedores</a>
      </li>
      <li>
        <a href={% url 'core:category_list' %}> <i class="bi bi-list-ul"></i> Categoria</a>
      </li>
      {% if user.is_authenticated %}
      <li>
        <a href="/logout"> <i class="bi bi-box-arrow-in-left"></i> Salir</a>
      </li>
      {% else %}
      <li>
        <a href={% url 'core:signup' %}> <i class="bi bi-person-check"></i> Registrarse</a>
      </li>
      <li>
        <a href=/signin> <i class="bi bi-box-arrow-in-right"></i> Ingresar</a>
      </li>
      {% endif %}
    </ul>
   </nav>
  </header>
  <main id="content">
    {% block content %}
    <h1>{{title2}}</h1>
   {% endblock content %}

  </main>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'js/sweet_alert.js' %}"></script>
</body>
</html>