core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    # Product views urls
    path("product_list/", views.product_List, name="product_list"),
    path("product_create/", views.product_Create, name="product_create"),
    path("product_update/<int:id>/", views.product_Update, name="product_update"),
    path("product_delete/<int:id>/", views.product_Delete, name="product_delete"),
    # Brands views urls
    path("brand_list/", views.brands_List, name="brand_list"),
    path("brand_create/", views.brands_Create, name="brand_create"),
    path("brand_update/<int:id>/", views.brands_Update, name="brand_update"),
    path("brand_delete/<int:id>/", views.brands_Delete, name="brand_delete"),
    # Supplier views urls
    path("supplier_list/", views.supplier_List, name="supplier_list"),
    path("supplier_create/", views.suppliers_Create, name="supplier_create"),
    path("supplier_update/<int:id>/", views.suppliers_Update, name="supplier_update"),
    path("supplier_delete/<int:id>/", views.suppliers_Delete, name="supplier_delete"),
    # Category views urls
    path("category_list/", views.category_list, name="category_list"),
    path("category_create/", views.category_Create, name="category_create"),
    path("category_update/<int:id>/", views.category_Update, name="category_update"),
    path("category_delete/<int:id>/", views.category_Delete, name="category_delete"),
    # Signup
    path("signup/", views.signup, name="signup"),
    path("logout/", views.signout, name="logout"),
    path("signin/", views.signin, name="signin"),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import F
from mysite.utils import valida_cedula, phone_regex
from django.core.validators import MinValueValidator


class ActiveBrandManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(state=True)


class Brand(models.Model):
    description = models.CharField("Articulo", max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    objects = models.Manager()  # Manager predeterminado
    active_brands = ActiveBrandManager()  # Manager filtrado por state=True

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        ordering = ["description"]
        indexes = [
            models.Index(fields=["description"]),
        ]

    def __str__(self):
        return self.description


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    ruc = models.CharField(max_length=13, validators=[valida_cedula])
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20, validators=[phone_regex])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]

    def __str__(self):
        return self.name


class ActiveProductManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(state=True)


class Product(models.Model):
    class Status(models.TextChoices):
        STORE = "RS", "Rio Store"
        FERRISARITO = "FS", "Ferrisariato"
        COMISARIATO = "CS", "Comisariato"

    description = models.CharField("Articulo", max_length=100)
    cost = models.DecimalField(
        "Costo Producto", max_digits=10, decimal_places=2, default=Decimal("0.0")
    )
    price = models.DecimalField(
        "Precio", max_digits=10, decimal_places=2, default=Decimal("0.0"), validators=[MinValueValidator(Decimal('0.0'))]
    )
    stock = models.IntegerField(
        validators=[MinValueValidator(0)],
        help_text="Stock debe estar en 0 y 10000 unidades",
        verbose_name="Stock",
    )
    iva = models.IntegerField(
        verbose_name="IVA", choices=((0, "0%"), (5, "5%"), (15, "15%")), default=15
    )
    expiration_date = models.DateTimeField("Fecha Caducidad", default=timezone.now)
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, related_name="product", verbose_name="Marca"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    supplier = models.OneToOneField(
        Supplier, on_delete=models.CASCADE, verbose_name="Proveedor"
    )
    categories = models.ManyToManyField("Category", verbose_name="Categoria")
    line = models.CharField(
        "Linea", max_length=2, choices=Status.choices, default=Status.COMISARIATO
    )
    image = models.ImageField(
        upload_to="products/", blank=True, null=True, default="products/default.png"
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    objects = models.Manager()  # Manager predeterminado
    active_products = ActiveProductManager()  #

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["description"]
        indexes = [
            models.Index(fields=["description"]),
        ]

    def __str__(self):
        return self.description

    @property
    def get_categories(self):
        return " - ".join(
            [c.description for c in self.categories.all().order_by("description")]
        )

    def reduce_stock(self, quantity):
        if quantity > self.stock:
            raise ValueError("No hay suficiente stock disponible.")
        self.stock -= quantity
        self.save()

    @staticmethod
    def update_stock(self, id, quantity):
        Product.objects.filter(pk=id).update(stock=F("stock") - quantity)


class Category(models.Model):
    description = models.CharField(verbose_name="Categoria", max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["description"]
        indexes = [
            models.Index(fields=["description"]),
        ]

    def __str__(self):
        return self.description


class Customer(models.Model):
    dni = models.CharField(
        verbose_name="Dni", max_length=13, unique=True, blank=True, null=True
    )
    first_name = models.CharField(verbose_name="Nombres", max_length=50)
    last_name = models.CharField(verbose_name="Apellidos", max_length=50)
    address = models.TextField(verbose_name="Dirección", blank=True, null=True)
    gender = models.CharField(
        verbose_name="Sexo",
        max_length=1,
        choices=(("M", "Masculino"), ("F", "Femenino")),
        default="M",
    )
    date_of_birth = models.DateField(
        verbose_name="Fecha Nacimiento", blank=True, null=True
    )
    phone = models.CharField(
        verbose_name="Telefono", max_length=50, blank=True, null=True
    )
    email = models.CharField(
        verbose_name="Correo", max_length=100, blank=True, null=True
    )
    image = models.ImageField(
        verbose_name="Foto",
        upload_to="customers/",
        blank=True,
        null=True,
        default="products/default.png",
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField(verbose_name="Activo", default=True)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ["last_name"]
        indexes = [
            models.Index(fields=["last_name"]),
        ]

    def save(self, *args, **kwargs):
        if self.first_name:
            self.first_name = self.first_name.upper()
        if self.last_name:
            self.last_name = self.last_name.upper()
        super(Customer, self).save(*args, **kwargs)

    @property
    def get_full_name(self):
        return f"{self.last_name} {self.first_name}"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class PaymentMethod(models.Model):
    description = models.CharField(verbose_name="Metodo Pago", max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    class Meta:
        verbose_name = "Metodo de Pago"
        verbose_name_plural = "Metodo de Pagos"
        ordering = ["description"]

    def __str__(self):
        return self.description


class Invoice(models.Model):
    customer = models.ForeignKey(
        Customer,
        on_delete=models.PROTECT,
        related_name="customer_invoices",
        verbose_name="Cliente",
    )
    payment_method = models.ForeignKey(
        PaymentMethod,
        on_delete=models.PROTECT,
        related_name="payment_invoices",
        verbose_name="Metodo pago",
    )
    issue_date = models.DateTimeField(
        verbose_name="Fecha Emision", default=timezone.now
    )
    subtotal = models.DecimalField(
        verbose_name="Subtotal", default=0, max_digits=16, decimal_places=2
    )
    iva = models.DecimalField(
        verbose_name="Iva", default=0, max_digits=16, decimal_places=2
    )
    discount = models.DecimalField(
        verbose_name="descuento", default=0, max_digits=16, decimal_places=2
    )
    total = models.DecimalField(
        verbose_name="Total", default=0, max_digits=16, decimal_places=2
    )
    payment = models.DecimalField(
        verbose_name="Pago", default=0, max_digits=16, decimal_places=2
    )
    change = models.DecimalField(
        verbose_name="Cambio", default=0, max_digits=16, decimal_places=2
    )
    status = models.CharField(
        verbose_name="Estado",
        max_length=1,
        choices=(("F", "Factura"), ("A", "Anulada"), ("D", "Devolucion")),
        default="F",
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField("Activo", default=True)

    class Meta:
        verbose_name = "Factura"
        verbose_name_plural = "Facturas"
        ordering = (
            "-issue_date",
            "customer",
        )
        indexes = [
            models.Index(fields=["issue_date"]),
            models.Index(fields=["customer"]),
        ]

    def __str__(self):
        return f"{self.id} - {self.customer}"


class InvoiceDetail(models.Model):
    invoice = models.ForeignKey(
        Invoice, on_delete=models.CASCADE, related_name="detail", verbose_name="Factura"
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT,
        related_name="Product",
        verbose_name="Producto",
    )
    cost = models.DecimalField(
        default=0, max_digits=16, decimal_places=2, null=True, blank=True
    )
    quantity = models.DecimalField(default=0, max_digits=10, decimal_places=2)

core/forms.py
from django import forms
from core.models import Product, Brand, Supplier, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "description",
            "price",
            "stock",
            "brand",
            "categories",
            "line",
            "supplier",
            "expiration_date",
            "image",
            "state",
        ]


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ["description", "state"]


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ["name", "ruc", "address", "phone", "state"]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["description", "state"]

templates/core/products/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="form-container">
    <form class="form-container" method="POST">
     {% csrf_token %}
     <h1 class="title">{{ title2 }}</h1>
     <h2>¿Desea Eliminar el Producto?
        <span>{{ product.id }} - {{ product.description }}</span>
     </h2>
     <div>
         <button class="btn blue" type="submit">Eliminar</button>
         <a class="btn red" href="{% url 'core:product_list' %}" >Regresar</a>
     </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/core/products/form.html
{% extends 'base.html' %}
{% block content %}
 <div class="container">
  <div class="form-container">
    <h2 class="title">{{title2}}</h2>
   
    <form method="post" enctype="multipart/form-data" class="card card-body">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-outline-success">
            <a href={% url 'core:product_list' %} class="btn btn-outline-danger"> Cancelar </a>
        </div>
    </form>
</div>
</div>
{% endblock content  %}

templates/core/products/list.html
{% extends 'base.html' %}
{% block content %}
   <div class="table-container">
    <br>
    <h1 class="title">{{ title2 }}</h1>
    <table class="styled-table">
      <thead>
        <tr>
          <th>Imagen</th>
          <th>Descripcion</th>
          <th>Precio</th>
          <th>Stock</th>
          <th>Marca</th>
          <th>Categorias</th>
          <th>Linea</th>
          <th>Proveedor</th>
          <th>Fecha Caducidad</th>
          <th>Estado</th>
          <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
        {% for item in products %}
          <tr>
          <td><img src={{item.image.url}} alt="" width="50px"> </td>
          <td>{{item.description}}</td>
          <td>{{item.price}}</td>
          <td>{{item.stock}}</td>
          <td>{{item.brand}}</td>
          <td>{{item.get_categories}}</td>
          <td>{{item.get_line_display}}</td>
          <td>{{item.supplier}}</td>
          <td>{{item.expiration_date |date:"Y-m-d"}}</td>
          <td>{% if item.state %}
               ✔
              {% else %}
               ➖
              {% endif %}
          </td>
          <td>
            <a href={% url 'core:product_update' item.id %}>✏️</a>
            <a href={% url 'core:product_delete' item.id %}>❌</a>
          </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
     <div class="form-group">
      <a class="btn btn-secondary" href={% url 'core:product_create' %}>Nuevo Producto</a>
     </div>
  </div>
  <style>
    .table-container {
        margin: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f9f9f9;
    }
    
    .title {
        text-align: center;
        font-size: 2em;
        color: #333;
    }
    
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: 'Arial', sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    
    .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    
    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
    }
    
    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }
    
    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }
    
    .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
    
    .styled-table tbody tr.active-row {
        font-weight: bold;
        color: #009879;
    }
    
    .form-group {
        text-align: center;
        margin-top: 20px;
    }
    
    .btn {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
    }
    
    .btn-secondary {
        background-color: #6c757d;
    }
    
    .btn:hover {
        background-color: #0056b3;
    }
    
    .btn-secondary:hover {
        background-color: #5a6268;
    }
    </style>
{% endblock content  %}